import type { Prisma, PrismaClient } from '@prisma/client';

// The single "include" shape we use everywhere so a returned Booking always
// carries the full trip context (line items + airline + airport + city etc.).
// Consumers get a fully-populated aggregate, not a bare row.
export const bookingInclude = {
  flightBookings: {
    include: {
      flightInstance: {
        include: {
          flightDefinition: {
            include: {
              airline: true,
              originAirport: { include: { city: true } },
              destinationAirport: { include: { city: true } },
            },
          },
        },
      },
    },
  },
  hotelBookings: {
    include: {
      roomType: {
        include: { hotel: { include: { city: true } } },
      },
    },
  },
  payments: true,
} as const satisfies Prisma.BookingInclude;

// A Booking with all its relations included, as defined by `bookingInclude`.
// This is the type returned by BookingRepository methods, and by BookingService methods.
// It is also the type returned by the Prisma client when using `include: bookingInclude`.
// Note: This type is not exported from the Prisma client, so we define it here for convenience.
// It is used in BookingService to return a fully-populated booking with all its relations.
// BookingGetPayload is a utility type provided by Prisma that takes a model and an include shape, and returns the type of the model with the included relations. In this case, we use it to get the type of Booking with all its relations included.
export type BookingWithRelations = Prisma.BookingGetPayload<{
  include: typeof bookingInclude;
}>;

export class BookingRepository {
  constructor(private readonly prisma: PrismaClient) {}

  async findById(id: number): Promise<BookingWithRelations | null> {
    return this.prisma.booking.findUnique({
      where: { id },
      include: bookingInclude,
    });
  }

  async findByReference(
    reference: string,
  ): Promise<BookingWithRelations | null> {
    return this.prisma.booking.findUnique({
      where: { reference },
      include: bookingInclude,
    });
  }

  // Find a booking by its idempotency key. This is used to ensure that a booking is only created once, even if the request is retried. idempotency keys are generated by the client and should be unique for each booking attempt. If a booking with the same idempotency key already exists, it will be returned instead of creating a new one.
  async findByIdempotencyKey(
    key: string,
  ): Promise<BookingWithRelations | null> {
    return this.prisma.booking.findUnique({
      where: { idempotencyKey: key },
      include: bookingInclude,
    });
  }
}
